package com.ssm.chapter.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "AWDTEAM")
public class AwdteamEntity implements java.io.Serializable {
	/** 版本号 */
	private static final long serialVersionUID = -5242204201941391237L;

	/* This code was generated by TableGo tools, mark 1 begin. */

	/** id */
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 3)
	private Integer id;

	/** teamid */
	@Column(name = "TEAMID", nullable = true, length = 3)
	private Integer teamid;

	/** eventid */
	@Column(name = "EVENTID", nullable = true, length = 3)
	private Integer eventid;

	/** flag */
	@Column(name = "FLAG", nullable = true, length = 100)
	private String flag;

	/** source */
	@Column(name = "SOURCE", nullable = true, length = 3)
	private Integer source;

	private String ipaddr;
	private String states;
	/* This code was generated by TableGo tools, mark 1 end. */

	/* This code was generated by TableGo tools, mark 2 begin. */

	/**
	 * 获取id
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 设置id
	 * 
	 * @param id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 获取teamid
	 * 
	 * @return teamid
	 */
	public Integer getTeamid() {
		return this.teamid;
	}

	/**
	 * 设置teamid
	 * 
	 * @param teamid
	 */
	public void setTeamid(Integer teamid) {
		this.teamid = teamid;
	}

	/**
	 * 获取eventid
	 * 
	 * @return eventid
	 */
	public Integer getEventid() {
		return this.eventid;
	}

	/**
	 * 设置eventid
	 * 
	 * @param eventid
	 */
	public void setEventid(Integer eventid) {
		this.eventid = eventid;
	}

	/**
	 * 获取flag
	 * 
	 * @return flag
	 */
	public String getFlag() {
		return this.flag;
	}

	/**
	 * 设置flag
	 * 
	 * @param flag
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/**
	 * 获取source
	 * 
	 * @return source
	 */
	public Integer getSource() {
		return this.source;
	}

	/**
	 * 设置source
	 * 
	 * @param source
	 */
	public void setSource(Integer source) {
		this.source = source;
	}

	public String getIpaddr() {
		return ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	public String getStates() {
		return states;
	}

	public void setStates(String states) {
		this.states = states;
	}

	/* This code was generated by TableGo tools, mark 2 end. */
}