package com.ssm.chapter.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "DOCKER")
public class docker implements java.io.Serializable {
	/** 版本号 */
	private static final long serialVersionUID = 4335286732416837447L;

	/* This code was generated by TableGo tools, mark 1 begin. */

	/** id */
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 3)
	private Integer id;

	/** eventid */
	@Column(name = "EVENTID", nullable = true, length = 3)
	private Integer eventid;

	/** model */
	@Column(name = "MODEL", nullable = true, length = 100)
	private String model;

	/** ipaddr */
	@Column(name = "IPADDR", nullable = true, length = 100)
	private String ipaddr;
	@Column(name = "count", nullable = true, length = 10)
	private int count;

	/* This code was generated by TableGo tools, mark 1 end. */

	/* This code was generated by TableGo tools, mark 2 begin. */

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	/**
	 * 获取id
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * 设置id
	 * 
	 * @param id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * 获取eventid
	 * 
	 * @return eventid
	 */
	public Integer getEventid() {
		return this.eventid;
	}

	/**
	 * 设置eventid
	 * 
	 * @param eventid
	 */
	public void setEventid(Integer eventid) {
		this.eventid = eventid;
	}

	/**
	 * 获取model
	 * 
	 * @return model
	 */
	public String getModel() {
		return this.model;
	}

	/**
	 * 设置model
	 * 
	 * @param model
	 */
	public void setModel(String model) {
		this.model = model;
	}

	/**
	 * 获取ipaddr
	 * 
	 * @return ipaddr
	 */
	public String getIpaddr() {
		return this.ipaddr;
	}

	/**
	 * 设置ipaddr
	 * 
	 * @param ipaddr
	 */
	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	/* This code was generated by TableGo tools, mark 2 end. */
}